apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-read-google-clouddns
  namespace: cert-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: eso-read-google-clouddns-secrets
  namespace: external-dns
rules:
- apiGroups: [""]
  resources:
  - secrets
  - secrets/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - authorization.k8s.io
  resources:
  - selfsubjectrulesreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eso-read-google-clouddns-secrets-rb
  namespace: external-dns
subjects:
- kind: ServiceAccount
  name: sa-read-google-clouddns
  namespace: cert-manager
roleRef:
  kind: Role
  name: eso-read-google-clouddns-secrets
  apiGroup: rbac.authorization.k8s.io