apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: argocd
spec:
  project: default

  sources:
  - repoURL: https://helm.astronomer.io
    chart: airflow
    targetRevision: v1.17.19
    helm:
      valueFiles:
        - $values/helm-values/airflow-values.yaml

  - repoURL: https://github.com/tobiasfuhge/data-engineering-project.git
    targetRevision: HEAD
    ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: airflow

  syncPolicy:
    automated:
      prune: true
      selfHeal: true