apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jupyterlab
  namespace: argocd
spec:
  project: default

  sources:
  - repoURL: https://jupyterhub.github.io/helm-chart/
    chart: jupyterhub
    targetRevision: 4.3.2
    helm:
      valueFiles:
        - $values/helm-values/jupyterlab-values.yaml
  - repoURL: https://github.com/tobiasfuhge/data-engineering-project.git
    targetRevision: main
    ref: values
    
  destination:
    server: https://kubernetes.default.svc
    namespace: python-ide

  ignoreDifferences:
  - group: ""
    kind: Secret
    name: python-ide-hub
    jsonPointers:
    - /data/hub.config.ConfigurableHTTPProxy.auth_token
    - /data/hub.config.CryptKeeper.keys
    - /data/hub.config.JupyterHub.cookie_secret

  syncPolicy:
    automated:
      prune: true
      selfHeal: true