apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jupyterlab
  namespace: argocd
spec:
  project: default

  sources:
  - repoURL: https://jupyterhub.github.io/helm-chart/
    chart: jupyterhub
    targetRevision: 4.3.2
    helm:
      valueFiles:
        - $values/helm-values/jupyterlab-values.yaml
  - repoURL: https://github.com/tobiasfuhge/data-engineering-project.git
    targetRevision: main
    ref: values
    
  destination:
    server: https://kubernetes.default.svc
    namespace: python-ide

  ignoreDifferences:
  - group: apps
    kind: Deployment
    name: hub
    jsonPointers:
    - /spec/template/metadata/annotations/checksum~1secret
    - /spec/template/metadata/annotations/checksum~1config-map
  - group: apps
    kind: Deployment
    name: proxy
    jsonPointers:
    - /spec/template/metadata/annotations/checksum~1auth-token
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true