apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://bitnami-labs.github.io/sealed-secrets/
    chart: sealed-secrets
    targetRevision: 2.18.0

  destination:
    server: https://kubernetes.default.svc
    namespace: sealed-secrets

  syncPolicy:
    automated:
      prune: true
      selfHeal: true