apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spark
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://charts.bitnami.com/bitnami
    chart: spark
    targetRevision: 10.0.3
    helm:
      valueFiles:
        - $values/helm-values/spark-values.yaml
  - repoURL: https://github.com/tobiasfuhge/data-engineering-project.git
    targetRevision: main
    ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: spark

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
