apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spark
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tobiasfuhge/data-engineering-project.git
    targetRevision: main
    path: charts/spark
    helm:
      valueFiles:
        - ../../helm-values/spark-values.yaml
  
  destination:
    server: https://kubernetes.default.svc
    namespace: spark

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true