apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-egress-to-data-storage-mlops
  namespace: mlops
spec:
  podSelector:
    matchLabels:
      app: mlflow
  policyTypes:
  - Egress
  egress:
  # Zugriff auf MinIO + Postgres
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: data-storage
    ports:
    - protocol: TCP
      port: 9000   # MinIO
    - protocol: TCP
      port: 5432   # Postgres
  # Zugriff auf DNS (CoreDNS)
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
      podSelector:
        matchLabels:
          k8s-app: kube-dns
    ports:
    - protocol: UDP
      port: 53
