---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: airflow-db-secret
  namespace: airflow
spec:
  encryptedData:
    connection: AgBUcQJnk1EO3cEn51shg8/pwmocDTRRaFNfw86fsG//LmdQbuVK1jVIrmLLgc6d1bmDGhtbx3oV8Wn5RbLCx6YqIHnprqryQZkZUEWykMGTVEOyNNhv5OuoJrpdvvlQej9PMHD18MuTIozhJH/gUtKRseoPOfxggAj63uSoJVqp1HgFzbVXtKiO3LHn9I+bxRkNRBvGGK75/RgMi5fRs5UgVkjaN+cJyIe6lla+9iUuY0VK63BJSwhxwkCWHkNhB2kJHCRw5loBtM7Q7EuIR9Z81Ml4Z6zpUHch2yiJskLTwJUUH3UAunBidNdNRowyZgy02BnM41qTkJeB+FlPxRNxdS5TIyfU9xkW6ukOJRsYeABdOQISNmZPuFGUfE+TnqPaY3EOptLngUst1gPlVp0JWvTwp7t1M2IC6GuCDYWGP0dojd1Hp7DJv37acVhIIRVcWJwLPBmkdafPNJhErHMLiz9AXjqNzPdGBCv5R3W+NeWq3PJJ4lSrqIE8N4y0vIoFQq/WZxolls8AXvgVTtgYl2wqVCSmHk/+tvUZqL/D60Edp7cQFuPnTACc6YvHwS35urci5k6upeTEbOdwyFeLCS+QEw0ss2g1ZYJg16OiBBHVpFmuSgOTO4trQ7MBgOKrpznIBwN69lBIhG7LPloglKn1r2Iqkqjy0bZzZTcjdpPUnaNhyQcNekjGSmN1JcB6nssfnYnSgBdcfo1xjNxhe/2x0yKUnT9LUHD/32wzzr5U1htvG1upjc8h2GQ6cJ4Ldo8gVXkUq6p0BDwU/J0HH/1JxRmdaLzTM6ICBdjeDQ==
  template:
    metadata:
      name: airflow-db-secret
      namespace: airflow
