---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: prometheus-stack
spec:
  encryptedData:
    admin-password: AgBGrlY31kxA6fl45RQs0jE7ppV+qFizRqBI2wUQsCvAwEawto9eIXAV5S7RgZBEfn6hrLf8n0xZKGM0yLNrECqJs+Gzm3IdGI1g6HDmZKUfInaQODzTVTxYpDuxiX4KRNoanEpCDgo0pedRNLKjuFOK8FbO/lrLlX34LjOHiCIiu/qAWsSX+Y735nynbzqLHsFsRX20kG8B8p0onZbxPrsi38M/lWtF6MvClT1vbjskg1osCUPtyuuHefHyvkCHdi2giXawCtZtXyHaznMelSwiC8Zm8ftX4I3Luft7N8vfkmtqCPVU4cU4kzOSHlJVeMhQ+2mbvWM1YOgKZdga54fOW0GVUVfMOrOfntkB1Bn/EmMHb6y6wtIAV2433D4z1VtEf9hXfAIJcdOanpFlKMpcg8Kw+a8fSuqVvRlhvYIdO/xgc4FYtkeerutsC/j+v5EGtnwkS9OeofxGm2pzbAGbdNoBrnzh3eE16pCj5i3aI4/mC+pWI0Dymn6L7QCimj1utzliEjbRkiCX+JKY89+lRXog9rpW9ZttIKba+EOFtpilMC0rw75usWradMy8/5zGvAU7wFvpaSyWDgX1WICmMWzbhRmFjM5ikKzR9BLhfRTjYMKPWbJq5clW6mUiysFxO6ncnAfn8jTepJ81SuIeAZ2JzQYB+HSFZYJtOt6HSt0+649HYFB23h30Wwe8TiA9D5kavWHAQfVa9hU=
    admin-user: AgAUMPMASbRIZZhgzm1FGe9GKYMJt155mfEy58pkq+UQ1bVkQUt5reAk3IT1Kjwzzq2E+sRL2fM4ES5wfoF4pK/Ou1/qku8I6TyRxP1R5WJ6w4xK84F/W2Jt6qqg3jkgYXGcfDonpVtL/mQf7nLKJMUxzGJ1v0CSfd5YeDZwKsyALdncjMq1fox+ccMRfu/Du5hsmAmZedJYXRijXiEW1UI5ZI20PZ53iF//s4rnML2969E4zSOzYQ33mZ6Yh8K6yUTOz7lBWcIHLbbRP2YZgz8y2LdBzxHaKA8huNY7E45iwbhF9v71Pwhq+zoqOqusNa9ZdzlvgykPuIGdeGB84TZDk4WiXpS4+k6KVUUNspje2FuiUdmaryp+k7wxRcq25ilJ+Ucenero8kmMsNTpgDwAsoK8DTE3cvtfbvxLjXiEeBrVOIVS5Pp2+yKgwTONNP6n25QAWroVjW9KoIfU3GWWJajgYGM1xLTxnMvbnjgjHoHaRyK8H7eg5xz58aSZGwC6N6gqbQyU4l+Xo7LoPz3R+1dLgBFoMMlXT3goFSsdIsJNeUNcDG9hczv85QtP6Sz5RGwjgHNxEqHns2LW9uSK/hkgv7R6rHraJqSHIB4CqV1+lohK3IFuOD1HDtvR7JdT099KGDpOOakh/JkGfKheBSi3P1ekxmCStRL2v2+XYRueb00RySofeCedP+6RHgxs/XBn3w==
  template:
    metadata:
      name: grafana-admin
      namespace: prometheus-stack
