---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-admin
  namespace: data-storage
spec:
  encryptedData:
    postgres-password: AgAbEpKIh0d5JSMh2+UF6Tsx8lFq1elCw2ariRGNtfQ4IYUw0JNgX12eEOjKqQyqt5Hrd+Iw3m26kbosIHs8Kql3Y0AO0H2ERLiKwRKUTOjY2t7BQCMqAv7SLrw3fRDs1kWP5AVgYGhOXiBgY1GrgLI3euFIJGYSf0NtfrOgqxChtvGrBJr8MMnxgdRbAL9sUc/A920ajZXOoJBdLdfqryCyI6pISU3ivztQ7qi22X8xcTtZArsFhHJVcpekWlLJX1OB97TXg5kjMI3vWoHGjrhZGlSqwf40REne+eH3YrIM0agqOkIg3vkwgOfEkjTZn+/UjKilUdpPanDYjBLNK3AFzK3oImuqcxbNDMdEE97TyNXIz7LesJeamuxVJC45xmv5RaC33pQkPPTMA64srCUnNaOF6vtFY2UXnfx3+Crvi/SUvCpslL+Mp33X3AzfjF1sJsWrcOuXpXDrMZ+P718MfGtDIZxWT8j9q/G5I6fNUBg1hF3Wd1y85mEqFMfeZoCEW+Z28W+Sv9PrdxxVYikwmXyqjC3Ko1lSGjOq0bM5xvfXhQoaeALeHdtg0heeZ1rjFm122I/Y1EFDYuY/TYEP3JNT7t2W8ne5VisvQtssu5w2BNhz1eSyeV4+JqCbmxloKwHk30nck10SWd605zClLFkG/7NWMRycZ+oywa1MwnZF9TwIddrOnUb/kqTxfu3aAxjMQ6aC68o+
    postgres-user: AgAu69cw2E/rF6pM/bLUztMz1UayFkaTTbtL+RGEhfs5P1AxOYMFyG8ODSg+0u33GRpCabwo4cAseHS8Yq0TpZPPshdmkFq24ws8c47cdrAnlrZUDaHqRF2RNDi/vgvA4Ks6N86VETRBci031XqLNxPEpQdW4vScLKlTT98epfUTGnozxHp80Gs2FyInYdwWzLlEtCyqWROH/bAR0sF2Rhco2IgU/0KwrM5273r5m60deQRR6N9zdM20soCtx7Kjd6RKbSFLfRUdaGkXUPkh60et46bBROd4Tca+7WoGqL1B2x1Mz3G4/KWA7hogEEh47EfAYG60GQ0GWg+bPNcnqfP0K9JsFSKPllRqS91nq9s518jK8lsr8MeaA7Dh+3pLf3vztc0sJskqy7j4c7GfTeObQqEEBJAq5CkA1D1PF/jVM2rqkEIFSB8KdRmJJBQKtcOxNC8qF+Ar+6rkFU8Vqge6F79PabSDPcT+EUs1/nl0gKRnvK/DQYra8VkHXIyeJcLabnHISP9TuMYlmHvy0dMEjEL9Eg6l27FYI3DCUtM8t3emphk3FEakkhmhDLNih35SCiWGVyLpLIPAS5GeGGLSPLg5Al96xhsaHr7JzwGdvsTSP7SON2v3Xmwa2wBBQ1fHqiB32Vp3j3xngQZwFD1lv+XotlB27Te9MJx+1RYzVMSoPFbQSQsBxkCizCnsr+1ldnmMSA==
  template:
    metadata:
      name: postgres-admin
      namespace: data-storage
