---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: renovate-git-token
  namespace: renovate
spec:
  encryptedData:
    token: AgCcaeP9pVIe3d+S4ydmyp8TiS8+oxD+Olj/k6FfSZLA7XipmzijfyXqbkSHTke8qPb2n6qkfTZszStC7sZWWE89B5FzCgc7ev7CVXWFJNA+7OeLpz/bRBXVVvKf0vBrek6pSGwbN0BoUHs+Up5yhWUs8Hm8BScJyr9dEsihBgckeOSjmbxnmGi/MI70Q4cD8IXPMkxXNHzQESxTzCR4eAC8157uZb6rxh5MdviM6lpbfPETbQvvuWVQ8P358kT+dlzd552GuB48KM03uFXVBiHA2JBJIOWgsFH3vH6GYmYyeOeKFcjYKEZZQ1UfZ40kKpnIQda3fVMda/tOROLG/JY/iHLUqOzfc/EgQlUXo5bOtZdwuAYvWHlJHMFPX/4YUdGGVdShZsBINqZW834nW5bKB1BwWC9ChFxyc2ed0rMEXvSLDe5WI6yjfU5+7ni/Syn6O2/kRohuUf9YIY7a7252ada+tDPvCUjkZLpfsq7N3X0+16fIUAt9XyF2dYa9KKCyRT6u/xkVlL0UUWb1+tTGz9MOEZyuFxUc0doA6uPDU7XCBa62KDjoBduxJVbwfQW3eumL/s+5J4086nMAyI4lJ63vWNKNGWEu9l85tbNQnwis6dAVbdDo9rAHg5K0rdtoNKiolfKhsIIHlp8nyuKV5zk1C0QbsrdbNwgwOo2mfBRtJQ3+oPanwFYOVNGZQu3+fcXD3Z5yEVWb2gplk5WQw655unNPC9LK28R/Iwp+BlYSCSc/b4pZ
  template:
    metadata:
      name: renovate-git-token
      namespace: renovate
