apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: airflow-statsd-monitor
  namespace: airflow
  labels:
    release: prometheus-stack 
spec:
  namespaceSelector:
    matchNames:
      - airflow
  selector:
    matchLabels:
      component: statsd
      release: airflow
  endpoints:
  - port: statsd-metrics
    interval: 30s
    path: /metrics